---
spring:
    config.activate.on-profile: default
    sql.init.platform: h2
    h2:
        console:
            settings:
                web-allow-others: true
cds:
    data-source.auto-config.enabled: false
    security:
        authentication:
            mode: dummy
---
spring:
    config.activate.on-profile: cloud
cds:
    sql.hana.search:
        fuzzy: true
        fuzzinessThreshold: 0.9
    security:
        xsuaa:
            enabled: true
            binding: JavaAuth
---
management:
    endpoint:
        health:
            show-components: always
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                # include: health
                include: "*"
    health:
        defaults:
            enabled: true
        ping:
            enabled: true
        db:
            enabled: true
---
spring:
    profiles:
        active: default
server:
    port: 4004
